### ISSUE TITLE
gawk strtonum?

### ISSUE THREAD

**Issue by enh** [onetrueawk/awk#35]
if i sent a patch adding gawk's strtonum ([described here](https://www.gnu.org/software/gawk/manual/html_node/Strtonum-Function.html)), would there be any interest in that? it seems like parsing hex is otherwise quite awkward.

i'm interested in the more general question of what would be accepted, but strtonum is the only gawk extension that i've seen Android OEMs using in practice so far, to pull constants out of .h files. (we've switched them over to one-true-awk even on the host when *building* Android for the Q release.) my suggested workaround is to just use awk to cut out the constant, and then use `$(( ))` shell arithmetic to convert hex to decimal.

i don't know how you'd want to measure whether something was generally useful enough/in widespread enough use. as perhaps an argument _against_ strtonum, it looks like busybox's awk only implements the [gawk bitwise functions](https://www.gnu.org/software/gawk/manual/html_node/Bitwise-Functions.html#Bitwise-Functions) and [gawk time functions](https://www.gnu.org/software/gawk/manual/html_node/Time-Functions.html#Time-Functions), so they at least haven't felt the need for strtonum yet.

(aside: [mawk](https://invisible-island.net/mawk/manpage/mawk.html) has the time functions too, so it looks like one-true-awk is the holdout there. i can find several users of `systime` in awk scripts quite easily, but not any of the other functions.)

anyway, happy to do the work, but was curious whether there's a policy and what that is... thanks!

**Comment by arnoldrobbins** [comment]
Hi. I had a brief discussion with @onetrueawk but did not reach any hard conclusions. There is no official policy as such, other than "the usual reluctance to add yet more features, however minimal."  Before adding code here, would one or the other of the following options meet your needs?

1. Create a shell script, call it `awkplus` with the contents
`exec awk -f /path/to/strtonum.awk "$@"`
And where `strtonum.awk` is the code from [the portable version of strtonum in the gawk doc](https://www.gnu.org/software/gawk/manual/html_node/Strtonum-Function.html). The code itself is in the public domain (see `awklib/eg/lib/strtonum.awk` in the gawk distribution).  Then educate your developers to use that script instead of using `awk` directly.

2. Making your own fork of this code base for Android development and adding strtonum to it.

Thanks!

**Comment by enh** [comment]
2 is what i'm most trying to avoid --- i think the world needs One True awk more than it needs Yet Another Slightly Different awk. (i was very pleased to see the Apple changes go in the other day, since macOS tends to cause me the most portability problems in general.)

in the specific case i have, i can just move the SoC vendor over to sed and shell arithmetic --- they really don't need awk at all. so until/unless i have a lot more use cases, i just plan on doing nothing.

my deeper question really was "is it a project goal to reduce some of these awk portability issues by implementing the most common extensions" --- because if so i'd happily devote some of my time to strtonum+the bitwise functions+the time functions, because the more people who can just use one-true-awk as-is the better for me (because it's now on Android devices and used by the Android build system). and obviously, i'd rather be prepared than be caught by surprise :-)

but it sounds like the answer is "not particularly, until/unless we have good specific cases". so i'll go away again and only come back if/when i have a more compelling need. (i do worry a bit about the ones busybox awk added --- my assumption is that they _will_ have had specific important use cases, building the Linux kernel, say, and that i'll hit them eventually.)

thanks!

**Comment by arnoldrobbins** [comment]
Thanks for understanding; I am not convinced that it's a good idea to saddle every other awk with the mistakes of my overenthusiastic youth.  :-)  Please stay in touch if solid use cases come up in other contexts.
