### ISSUE TITLE
UTF-8: multiple bracket expressions containing character classes aren't matched

### ISSUE THREAD

**Issue by McDutchie** [onetrueawk/awk#45]
In UTF-8 locales, multiple bracket expressions containing character classes aren't matched correctly.

Symptoms:

```sh
$ echo 'é' | awk '/[[:alpha:]]/'               # ok
é
$ echo 'éé' | awk '/[[:alpha:]][[:alpha:]]/'   # NOT ok
(no output)
```

System: macOS 10.14.6. Using onetrueawk version 20190717.

My locale:

```sh
$ locale
LANG="nl_NL.UTF-8"
LC_COLLATE="nl_NL.UTF-8"
LC_CTYPE="nl_NL.UTF-8"
LC_MESSAGES="nl_NL.UTF-8"
LC_MONETARY="nl_NL.UTF-8"
LC_NUMERIC="nl_NL.UTF-8"
LC_TIME="nl_NL.UTF-8"
LC_ALL=
```

In an ISO-8859-1 locale (`LANG="nl_NL.ISO8859-1"`) this works fine.

**Comment by McDutchie** [comment]
See also: https://github.com/ThomasDickey/original-mawk/issues/62

**Comment by arnoldrobbins** [comment]
What kind of system are you on?  I find it interesting that

`$ echo 'é' | awk '/[[:alpha:]]/'`

works. For me on Linux, it produces no output (which is correct for the way the current code is).

I suppose I need to add a note to the man page. The One True Awk *does not support Unicode*. Period.  It is 8-bit clean, but it only understands 8-bit characters.

Sadly, it is unlikely that this will change, unless someone can be found to do the work. Speaking from experience, it is doable, but non-trivial, and neither BWK nor I have the time to do this.

**Comment by McDutchie** [comment]
As I specified: macOS 10.14.6.

Yes, very strange. Since a single character class bracket expression did match, I assumed UTF-8 support. If UTF-8 is not supported at all, then it seems like a bug to me that any of this matches. Non-ASCII UTF-8 characters only use bytes > 127, so it should be possible to rely on something like `match("é", /[[:alpha:]]/)` to detect UTF-8 support.

Note that the symptoms are identical between Apple's stock /usr/bin/awk (20070501 as patched by Apple to add bounds support) and version 20190717 as freshly compiled from git.

**Comment by McDutchie** [comment]
Experimenting some more. It appears that, on macOS, both onetrueawk and mawk simply match any high-bit UTF-8 character to a number of incorrect character classes.

```sh
for class in alnum alpha blank cntrl digit graph lower print punct space upper xdigit; do
    test -n "$(echo '😳' | awk "/[[:$class:]]/")" && echo "$class"
done
```

Output on my system (macOS 10.14.6 with awk version 20190717):

```
alnum
alpha
cntrl
graph
lower
print
```

Interestingly, onetrueawk and mawk give identical output.

gawk only outputs `graph`, `print` and `punct`. (Is an emoji punctuation?)

If the character is changed from the emoji to é, the output from onetrueawk and mawk changes:

```
alnum
alpha
graph
print
punct
upper
```

where gawk correctly outputs `alnum`, `alpha`, `graph`, `lower` and `print`.

**Comment by arnoldrobbins** [comment]
Thanks for the update. This points pretty strongly at the C library on Mac OS X.  I'm curious what you get if you compile and run this C program:

```C
#include <stdio.h>
#include <ctype.h>

int main(int argc, char **argv)
{
	printf("isalpha(303) = %d\n", isalpha(303 & 0xff));
	printf("isalpha(251) = %d\n", isalpha(251 & 0xff));
	return 0;
}
```

If either of them prints a 1, you'll know for sure it's the C library that is the culprit.

**Comment by arnoldrobbins** [comment]
Oops. Corrected version:

```C
#include <stdio.h>
#include <ctype.h>

int main(int argc, char **argv)
{
	printf("isalpha(0303) = %d\n", isalpha(0303 & 0xff));
	printf("isalpha(0251) = %d\n", isalpha(0251 & 0xff));
	return 0;
}
```

**Comment by arnoldrobbins** [comment]
By the way, even if one were to add support for multi-byte strings for things like `length()` and `substr()` the regular expression routines would also need updating, and *that* would be a true tar pit.

**Comment by McDutchie** [comment]
Unfortunately, the output of your test program (corrected version) on my system is:

```
$ ./test
isalpha(0303) = 0
isalpha(0251) = 0
```

…so it seems like some more detective work is needed. Any ideas?

**Comment by arnoldrobbins** [comment]
See lines 988-995 in b.c, where the code substitutes in the list of characters from 0 to 255 that match the given function.  Maybe running a debugger there would help; isalpha() should fail for non-letters but maybe it isn't doing so.

In any case, I don't have a modern Mac OS X system that I can work on, so you or someone else will have to trace it down in a debugger.

**Comment by arnoldrobbins** [comment]
Hi. What happens if you add

```C
setlocale(LC_CTYPE, "");
```

to the test program and then run it?  I forgot that by default C programs are in the `"C"` locale.

**Comment by McDutchie** [comment]
The output with the `setlocale` added is:

```
$ ./test
isalpha(0303) = 1
isalpha(0251) = 0
```

**Comment by arnoldrobbins** [comment]
So that exactly explains why you're seeing what you're seeing. IMHO it's a bug in the MacOS X C library, since you're in a UTF-8 locale.

In short, there's nothing to be done in the One True Awk code base. Thanks.

**Comment by cesss** [comment]
@arnoldrobbins @onetrueawk I'm a bit confused about the conversation in this issue, because I asked some time ago if One True Awk supported UTF-8 (see https://github.com/onetrueawk/awk/issues/22) and the answer was negative... however, in this other issue the conversation seems to imply that UTF-8 encoded text should be supported...

**Comment by arnoldrobbins** [comment]
Issue 22 was very clear. If your UTF-8 encoded text contains only characters in the ASCII subset of Unicode, you will have no problems. Otherwise, things will not work.

**Comment by cesss** [comment]
Yep, that's exactly what I meant: The `'é'` character doesn't belong to the ASCII subset of Unicode, so when I read this issue I was surprised that the expected result was that such a character should work in One True Awk, rather than the kind of reply I'd suppose: that the behaviour was undefined because UTF-8 is not implemented.

**Comment by arnoldrobbins** [comment]
I don't understand your confusion. The conversation here is also very clear that Unicode is not supported.

What was strange was that MacOS X isalpha in McDutchie's locale treated a particular byte with the high bit set as if it were a valid alphabetic character, when it's not.  This led McDutchie to believe that Unicode was supported.  But the bug is in the Mac OS X C library, not in awk's code.

**Comment by mogando668** [comment]
although i haven't implemented the full Unicode13 "alpha" regex definition, i've written a few unicode-safe string functions that are nawk/mawk/gawk-cross-compatible, such as ordB( ) ordC( ) (anything _B suffix means byte level, _C means UTF8-level, so ordC( ) returns unicode code-point value, in base10 integer), chrB( ) chrC(), lengthB( ) lengthC( ), revB( ) revC( ), and substrB( ) substrC( ).

i'll try to get to writing the multi-awk compatible regex to emulate unicode classes, even for non-unicode aware variants for awk (i've written ones for korean japanese and chinese but not the more mainstream ones about alpha and graph since i had little personal need for european chars). i'm even testing some regex ideas so i could print out all 61,440 UTF-8 3-byte characters, already pre-sorted in unicode code-point order, with only 3 or 4 calls of gsubs( ). so far the idea worked for 2-byte ones.

in the meantime, if any of the above could be of any use, just lemme know and i'll paste the code right here
