### ISSUE TITLE
`split`, LOCALE, and POSIX.

### ISSUE THREAD

**Issue by mavenraven** [onetrueawk/awk#87]
Hey @arnoldrobbins! Thank you for your tireless work maintaining `nawk` and `gawk`!

I was recently working on awk script for converting fixedwidth text to delimited text (https://github.com/mavenraven/fixedwidth2csv/blob/master/fixedwidth2csv). I was testing the script against the common different awk implementations, and I noticed that `split` in nawk doesn't respect `LC_CTYPE`, e.g.

```
git clone https://github.com/onetrueawk/awk && cd awk && make && echo "🐈ello"| LC_CTYPE="en_US.UTF-8" ./a.out  '{ split($0, chars, ""); for (c in chars) { print chars[c] }}'
```
prints
```



e
l
l
o
```

. On the other hand,  for `gawk`:
```
echo "🐈ello"| LC_CTYPE="en_US.UTF-8" gawk '{ split($0, chars, ""); for (c in chars) { print chars[c] }}'
```
prints
```
🐈
e
l
l
o
```
and
```
echo "🐈ello"| LC_CTYPE="C" gawk  '{ split($0, chars, ""); for (c in chars) { print chars[c] }}'
```
prints
```




e
l
l
o
```
as expected.

The standard says:

LC_CTYPE
Determine the locale for the interpretation of sequences of bytes of text data as characters (for example, single-byte as opposed to multi-byte characters in arguments and input files), the behavior of character classes within regular expressions, the identification of characters as letters, and the mapping of uppercase and lowercase characters for the toupper and tolower functions.

I personally read this as `split` should support LOCALE, but it's not explicit.

I'm sure you're already aware of all this since you both maintain both projects. I was wondering if there was explicit decision made for `nawk` to not support this behavior, or if its a feature where a PR would be welcome?

Again, thanks for all of your hard work!

**Comment by arnoldrobbins** [comment]
Hi. Sorry for the delay in replying.  The issue is broader than just `split`.  Awk only supports 8-bit characters. It doesn't understand UTF-8 or any other character encoding.  Making it do so is more work than either I or @onetrueawk care to invest; the thorniest problem would be revising (or replacing) the regular expression matcher (there are options, but it's work that'd have to be done).

In terms of a PR, I think we want either all or nothing - fixing `split` without fixing the rest of Awk would only add to the confusion.  If you're interested in helping with the bigger solution, let me know and we can continue the discussion in private mail.

Thanks!

**Comment by mavenraven** [comment]
Ah yeah, that's what I figured. Thanks for the response!
