### ISSUE TITLE
is the code useful here?

### ISSUE THREAD

**Issue by YongHaoWu** [onetrueawk/awk#94]
run.c 1545line:
```
		(void) mbtowc(NULL, NULL, 0);	/* reset internal state */
		/*
		 * Reset internal state here too.
		 * Assign result to avoid a compiler warning. (Casting to void
		 * doesn't work.)
		 * Increment said variable to avoid a different warning.
		 */
		int unused = wctomb(NULL, L'\0');
		unused++;

```

`unused` and `wctomb(NULL, L'\0')` seems useless.

**Comment by YongHaoWu** [comment]
run.c 1545line:
```
		(void) mbtowc(NULL, NULL, 0);	/* reset internal state */
		/*
		 * Reset internal state here too.
		 * Assign result to avoid a compiler warning. (Casting to void
		 * doesn't work.)
		 * Increment said variable to avoid a different warning.
		 */
		int unused = wctomb(NULL, L'\0');
		unused++;

```

`unused` and `wctomb(NULL, L'\0')` seems useless.

**Comment by arnoldrobbins** [comment]
Note the explanations in the comment above the code. The call to `wctomb` resets the internal state. GCC complains if the return value is ignored (even if explicitly cast to void).  Furthermore, it then complains that the variable `unused` is assigned to but not otherwise use.  Thus the increment.  It's all spelled out pretty clealy.
